./asm.py database.db add-asm-instruction --file=test-cases/rdtsc.c --instr=rdtsc
./asm.py database.db add-asm-instruction --file=test-cases/pause.c --instr=pause
./asm.py database.db add-asm-instruction --file=test-cases/rdtscp.c --instr=rdtscp
./asm.py database.db add-asm-instruction --file=test-cases/empty.c --instr=""
./asm.py database.db add-asm-instruction --file=test-cases/xgetbv.c --instr=xgetbv
./asm.py database.db add-asm-instruction --file=test-cases/bsrl.c --instr=bsrl
./asm.py database.db add-asm-instruction --file=test-cases/crc32b.c --instr=crc32b
./asm.py database.db add-asm-instruction --file=test-cases/crc32l.c --instr=crc32l
./asm.py database.db add-asm-instruction --file=test-cases/crc32q.c --instr=crc32q
./asm.py database.db add-asm-instruction --file=test-cases/crc32w.c --instr=crc32w
./asm.py database.db add-asm-instruction --file=test-cases/mfence.c --instr=mfence
