./asm.py database.db add-asm-instruction --file=test-cases/rdtsc.c --instr=rdtsc
./asm.py database.db add-asm-instruction --file=test-cases/pause.c --instr=pause
./asm.py database.db add-asm-instruction --file=test-cases/rdtscp.c --instr=rdtscp
./asm.py database.db add-asm-instruction --file=test-cases/empty.c --instr=""
./asm.py database.db add-asm-instruction --file=test-cases/xgetbv.c --instr=xgetbv
./asm.py database.db add-asm-instruction --file=test-cases/bsr.c --instr=bsr
./asm.py database.db add-asm-instruction --file=test-cases/bsf.c --instr=bsf
./asm.py database.db add-asm-instruction --file=test-cases/crc32.c --instr=crc32
./asm.py database.db add-asm-instruction --file=test-cases/mfence.c --instr=mfence
./asm.py database.db add-asm-instruction --file=test-cases/sete.c --instr=sete
